---
defaults:
  docker:
    repositoryPrefix: taskcluster/taskcluster-
  workers:
    gcp:
      # the GCP project in which images are built and from which they are published
      project: taskcluster-builder
      # the folder containing the project
      folder: 944037250603
      # users with access to this project, comma-separated
      users: user:dmitchell@mozilla.com,user:jford@mozilla.com,user:pmoore@mozilla.com,user:haali@mozilla.com,user:wcosta@mozilla.com,user:coop@mozilla.com,user:bstack@mozilla.com,user:istorozhko@mozilla.com
